apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-serve
  labels:
    app: http-serve
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: http-serve
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: serve
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["serve", "--grpc", "grpc-internal:9090"]
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-internal
  labels:
    app: grpc-internal
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: grpc-internal
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: grpc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["grpc"]
          ports:
            - containerPort: 9090
          resources:
{{ toYaml .Values.resources | indent 12 }}
 
