apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /v1/.*
        backend:
          serviceName: http-serve
          servicePort: 8080
      - backend:
          serviceName: grpc-internal
          servicePort: 9090
