apiVersion: v1
kind: Service
metadata:
  name: http-serve
  labels:
    app: http-serve
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-serve
  selector:
    app: http-serve
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-internal
  labels:
    app: grpc-internal
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc-internal
  selector:
    app: grpc-internal
    release: {{ .Release.Name }}
